---

- name: get SSH keys from GitHub
  hosts: webserver
  remote_user: root
  tasks:
    - name: get ssh key from url
      uri:
        url: https://github.com/{{ item }}.keys
        return_content: true
      register: ssh_keys
      with_items:
      - diadzine
      - gmeylan
    - name: add SSH key labels to ~/.ssh/authorized_keys
      lineinfile:
        dest: ~/.ssh/authorized_keys
        line: "# {{ item }}"
      with_items:
      - diadzine
      - gmeylan
    - name: add SSH keys to ~/.ssh/authorized_keys
      lineinfile:
        dest: ~/.ssh/authorized_keys
        line: "{{ item.0.content }}"
        insertafter: "{{ item.1 }}"
      with_together:
        - ssh_keys.results
        - add_ssh_keys_from_github.usernames
      changed_when: false # FIXME
      when: "add_ssh_keys_from_github.usernames | count > 0"


# - name: set authorized keys taken from url
#   ansible.posix.authorized_key:
#     user: root
#     state: present
#     key: https://github.com/{{ item }}.keys
#   with item :
#   - carlosperezepfl
#   - mistur
#   - reyuce  
...

